'use client';
import {useState,useEffect,useRef} from 'react';
import {Microscope,Settings,BookOpen,Monitor,Upload,FileText,Search,Sparkles,Atom,ChevronRight,FolderHeart,Download,Maximize,HelpCircle,X,Check,ShieldCheck,Lightbulb,ArrowUpRight,FlaskConical,Clock,Trash2,KeyRound,LoaderCircle,RotateCcw,PencilLine} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {toast,Toaster} from 'sonner';
import {TEXT_LIMITS,textLimitError} from '@/lib/generation-limits.mjs';
import {catalog,simulationHTML,secureHTML,type Lesson} from '@/lib/simulations';
const subjects=['Vật lý','Toán học','Hóa học','Sinh học','Khoa học tự nhiên','Địa lý','Lịch sử','Ngữ văn','Tiếng Anh','Tin học','Công nghệ','Âm nhạc','Mỹ thuật','Giáo dục công dân','Giáo dục thể chất','Hoạt động trải nghiệm'];
function Choice({value,onChange,items,label}:{value:string,onChange:(v:string)=>void,items:string[],label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="field"><SelectValue/></SelectTrigger><SelectContent>{items.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select>}
function TextCount({field,value,id}:{field:'topic'|'details'|'revision',value:string,id:string}){const error=textLimitError(field,value);return <p id={id} role={error?'alert':undefined} style={{fontSize:'0.875rem',margin:'6px 0',color:error?'#b42318':'#52635e'}}>{value.length.toLocaleString('vi-VN')} / {TEXT_LIMITS[field].toLocaleString('vi-VN')} ký tự{error&&<> · {error}</>}</p>}
export default function Home(){
const [subject,setSubject]=useState('Vật lý'),[grade,setGrade]=useState('Lớp 8'),[topic,setTopic]=useState(''),[details,setDetails]=useState(''),[mode,setMode]=useState('topic'),[devices,setDevices]=useState<string[]>(['Máy chiếu + Laptop']),[files,setFiles]=useState<File[]>([]),[settings,setSettings]=useState(false),[help,setHelp]=useState(false),[key,setKey]=useState(''),[model,setModel]=useState(''),[models,setModels]=useState<string[]>([]),[checking,setChecking]=useState(false),[busy,setBusy]=useState(false),[view,setView]=useState('library'),[query,setQuery]=useState(''),[filter,setFilter]=useState('Tất cả'),[active,setActive]=useState<Lesson|null>(null),[saved,setSaved]=useState<Lesson[]>([]),[full,setFull]=useState(false),[editing,setEditing]=useState(false),[revision,setRevision]=useState('');
const revising=useRef(false);
const input=useRef<HTMLInputElement>(null),controller=useRef<AbortController|null>(null);
useEffect(()=>{try{const x=JSON.parse(localStorage.getItem('molab-lessons-v1')||'[]');if(Array.isArray(x))setSaved(x.filter(v=>v&&typeof v.id==='string'&&typeof v.title==='string'&&typeof v.html==='string').slice(0,30));}catch{}},[]);
function save(lesson:Lesson){const next=[lesson,...saved.filter(x=>x.id!==lesson.id)].slice(0,30);try{localStorage.setItem('molab-lessons-v1',JSON.stringify(next));setSaved(next);toast.success('Đã lưu trên thiết bị này.')}catch{toast.error('Bộ nhớ đầy. Hãy tải mô phỏng về máy.')}}
function remove(id:string){const next=saved.filter(x=>x.id!==id);try{localStorage.setItem('molab-lessons-v1',JSON.stringify(next));setSaved(next)}catch{toast.error('Không thể cập nhật bộ nhớ.')}}
function addFiles(list:FileList|null){if(!list)return;const accepted:File[]=[];for(const f of Array.from(list)){if(!/\.(pdf|png|jpe?g|webp|txt)$/i.test(f.name)){toast.error(`${f.name}: chỉ hỗ trợ PDF, ảnh hoặc TXT.`);continue}if(f.size>3*1024*1024){toast.error(`${f.name}: tối đa 3 MB.`);continue}accepted.push(f)}if(files.length+accepted.length>5)toast.error('Tối đa 5 file mỗi lần.');const next=[...files,...accepted].slice(0,5);if(next.reduce((sum,f)=>sum+f.size,0)>3*1024*1024){toast.error('Tổng dung lượng tối đa 3 MB cho mỗi yêu cầu.');return}setFiles(next)}
async function connect(){if(!key.trim())return toast.error('Vui lòng nhập API Key.');setChecking(true);try{const r=await fetch('/api/models',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key})});const d=await r.json() as {error?:string,models:string[]};if(!r.ok)throw Error(d.error);setModels(d.models);setModel(d.models.includes(model)?model:d.models[0]||'');toast.success('Đã xác minh kết nối và tải danh sách model.')}catch(e){toast.error(e instanceof Error?e.message:'Không kết nối được AI.')}finally{setChecking(false)}}
async function generate(){const error=textLimitError('topic',topic)||textLimitError('details',details);if(error)return toast.error(error);if(mode==='topic'&&!topic.trim())return toast.error('Hãy nhập chủ đề cần mô phỏng.');if(mode==='file'&&!files.length)return toast.error('Hãy tải lên ít nhất một file.');if(!key||!model){setSettings(true);return toast.info('Kết nối Gemini để tạo mô phỏng mới. Thư viện có thể dùng ngay.')}setBusy(true);controller.current=new AbortController();try{const data=new FormData();data.set('key',key);data.set('model',model);data.set('topic',topic);data.set('subject',subject);data.set('grade',grade);data.set('details',details);data.set('devices',devices.join(', '));if(mode==='file')files.forEach(f=>data.append('files',f));const r=await fetch('/api/generate',{method:'POST',body:data,signal:controller.current.signal});const d=await r.json() as {error?:string,title:string,description:string,html:string};if(!r.ok)throw Error(d.error);setActive({id:crypto.randomUUID(),title:d.title,subject,grade,description:d.description,kind:'ai',html:d.html});toast.success('Mô phỏng đã sẵn sàng. Hãy kiểm tra nội dung trước khi giảng dạy.')}catch(e){if(e instanceof Error&&e.name!=='AbortError')toast.error(e.message)}finally{setBusy(false)}}
async function revise(action:'regenerate'|'edit'){
if(revising.current||busy||!active)return;
if(action==='edit'&&textLimitError('revision',revision))return toast.error(textLimitError('revision',revision));
if(action==='edit'&&!revision.trim())return toast.error('Nhập nội dung cần thêm, bớt hoặc chỉnh sửa.');
if(!key||!model){toast.info('Hãy kết nối Gemini trong Cấu hình AI rồi mở lại mô phỏng để chỉnh sửa.');return;}
const source=active;
revising.current=true;setBusy(true);const abort=new AbortController();controller.current=abort;
try{
const data=new FormData();Object.entries({key,model,topic:source.title,subject:source.subject,grade:source.grade,details:'',devices:devices.join(', '),action,revision:action==='edit'?revision.trim():'',existingHtml:source.html||simulationHTML(source.kind)}).forEach(([k,v])=>data.set(k,v));
const r=await fetch('/api/generate',{method:'POST',body:data,signal:abort.signal});
const d=await r.json() as {error?:string,title:string,description:string,html:string};
if(!r.ok)throw Error(d.error||'Không cập nhật được mô phỏng.');
if(abort.signal.aborted)return;
setActive({...source,id:crypto.randomUUID(),title:d.title,description:d.description,html:d.html,kind:'ai'});setEditing(false);setRevision('');
toast.success(action==='edit'?'Đã chỉnh sửa mô phỏng. Nhấn lưu để giữ bản mới.':'Đã tạo lại mô phỏng. Nhấn lưu để giữ bản mới.');
}catch(e){if(e instanceof Error&&e.name!=='AbortError')toast.error(e.message+' Bản hiện tại được giữ nguyên.');}
finally{revising.current=false;setBusy(false);}
}
function download(l:Lesson){const blob=new Blob([secureHTML(l.html||simulationHTML(l.kind))],{type:'text/html;charset=utf-8'});const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download=l.title.replace(/[^\p{L}\p{N} -]/gu,'')+'.html';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
const list=(view==='saved'?saved:catalog).filter(x=>(filter==='Tất cả'||x.subject===filter)&&(!query||`${x.title} ${x.subject} ${x.description}`.toLocaleLowerCase('vi').includes(query.toLocaleLowerCase('vi'))));
return <><Toaster richColors position="top-center"/><header className="topbar"><a className="brand" href="/"><span className="brandmark"><Microscope/></span><span>TRỢ LÝ TẠO<span>MÔ PHỎNG<span className="brand-ai"> AI</span></span></span></a><nav><button className={view==='library'?'nav-active':''} onClick={()=>{setView('library');setQuery('');setFilter('Tất cả')}}><BookOpen size={17}/>Thư viện mô phỏng</button><button className={view==='saved'?'nav-active':''} onClick={()=>{setView('saved');setQuery('');setFilter('Tất cả')}}><FolderHeart size={17}/>Mô phỏng của tôi</button></nav><div className="top-actions"><button className="help-button" onClick={()=>setHelp(true)}><HelpCircle size={18}/>Hướng dẫn</button><button aria-label="Cấu hình AI" className="icon-button" onClick={()=>setSettings(true)}><Settings size={19}/></button><span className="teacher-avatar">GV</span></div></header>
<main className="workspace"><div className="breadcrumb">Không gian giáo viên <ChevronRight size={14}/><b>Phòng thực hành số</b></div><div className="page-heading"><div><div className="eyebrow">DẠY HỌC TRỰC QUAN · KHÁM PHÁ CHỦ ĐỘNG</div><h1>Biến kiến thức thành trải nghiệm<span>.</span></h1><p>Thiết kế mô phỏng tương tác, khơi mở tư duy trong từng bài học.</p></div><span className="workspace-label"><ShieldCheck size={16}/> Dành cho giáo dục</span></div>
<div className="workspace-grid"><aside className="setup panel"><div className="setup-heading"><span className="setup-icon"><Monitor size={25}/></span><div><h2>Thiết lập mô phỏng</h2><p>Từ ý tưởng đến bài học sinh động</p></div></div><div className="setup-body"><h3><span className="step">1</span>THÔNG TIN CƠ BẢN</h3><label className="label"><BookOpen size={13}/> MÔN HỌC</label><Choice value={subject} onChange={setSubject} items={subjects} label="Môn học"/><label className="label">ĐỐI TƯỢNG HỌC SINH</label><Choice value={grade} onChange={setGrade} items={Array.from({length:12},(_,i)=>`Lớp ${i+1}`)} label="Lớp"/><Tabs value={mode} onValueChange={setMode} className="input-tabs"><TabsList><TabsTrigger value="topic"><FileText/>Nhập chủ đề</TabsTrigger><TabsTrigger value="file"><Upload/>Tải file bài tập</TabsTrigger></TabsList><TabsContent value="topic"><label className="label" htmlFor="topic">CHỦ ĐỀ CHI TIẾT <em>*</em></label><textarea id="topic" value={topic} aria-describedby="topic-count" aria-invalid={topic.length>TEXT_LIMITS.topic} onChange={e=>setTopic(e.target.value)} placeholder="Ví dụ: Định luật Ohm, cấu trúc nguyên tử, đồ thị hàm số…" rows={3}/><TextCount field="topic" value={topic} id="topic-count"/><div className="suggestions"><span>Thử ngay:</span>{['Định luật Ohm','Khúc xạ ánh sáng'].map(t=><button key={t} onClick={()=>setTopic(t)}>{t}</button>)}</div></TabsContent><TabsContent value="file"><label className="label">TẢI FILE BÀI TẬP <em>*</em></label><button className="dropzone" onClick={()=>input.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();addFiles(e.dataTransfer.files)}}><Upload size={32}/><b>Kéo thả file vào đây</b><span>hoặc nhấn để chọn từ thiết bị</span><div><i>Hình ảnh</i><i>PDF</i><i>TXT</i></div><small>Tối đa 5 file · Tổng dung lượng ≤ 3 MB</small></button><input hidden ref={input} type="file" multiple accept=".pdf,.png,.jpg,.jpeg,.webp,.txt" onChange={e=>{addFiles(e.target.files);e.target.value=''}}/>{files.map((f,i)=><div className="file-row" key={i}><FileText size={14}/><span>{f.name}</span><button aria-label={`Xóa ${f.name}`} onClick={()=>setFiles(files.filter((_,j)=>j!==i))}><X size={15}/></button></div>)}</TabsContent></Tabs>
<h3 className="advanced-title"><span className="step muted">2</span>CHI TIẾT NÂNG CAO</h3><label className="label" htmlFor="details">THÔNG SỐ ĐIỀU CHỈNH <span>Không bắt buộc</span></label><textarea id="details" value={details} aria-describedby="details-count" aria-invalid={details.length>TEXT_LIMITS.details} onChange={e=>setDetails(e.target.value)} placeholder="Góc tới, điện trở, khối lượng, nhiệt độ…" rows={2}/><TextCount field="details" value={details} id="details-count"/><label className="label">ĐIỀU KIỆN SỬ DỤNG</label><div className="device-grid">{['Máy chiếu + Laptop','Chỉ có điện thoại','Không có internet','Có internet ổn định'].map(x=><label key={x}><Checkbox checked={devices.includes(x)} onCheckedChange={v=>setDevices(v?[...devices.filter(d=>!((x==='Không có internet'&&d==='Có internet ổn định')||(x==='Có internet ổn định'&&d==='Không có internet')||(x==='Chỉ có điện thoại'&&d==='Máy chiếu + Laptop')||(x==='Máy chiếu + Laptop'&&d==='Chỉ có điện thoại'))),x]:devices.filter(d=>d!==x))}/>{x}</label>)}</div><button className="button outline wide" onClick={()=>{setView('library');setQuery(topic.trim());setFilter('Tất cả');document.getElementById('library')?.scrollIntoView({behavior:'smooth',block:'start'})}}><Search size={18}/>Tìm kiếm thư viện</button><button disabled={busy} className="button primary wide" onClick={generate}>{busy?<LoaderCircle className="spin" size={18}/>:<Sparkles size={18}/>} {busy?'Đang tạo mô phỏng…':mode==='file'?'Tạo mô phỏng từ file':'Tạo mô phỏng AI'}<span className="beta">BETA</span></button>{busy&&<button className="cancel" onClick={()=>controller.current?.abort()}>Hủy tạo</button>}<div className="private-note"><ShieldCheck size={13}/> API Key chỉ giữ trong phiên làm việc</div></div></aside>
<section className="main-content" id="library"><div className="welcome-card"><div className="welcome-icon"><FlaskConical size={24}/></div><div><h2>Một bài học. Vô vàn khám phá.</h2><p>Bắt đầu với mô phỏng có sẵn, hoặc tạo điều mới mẻ bằng AI.</p></div><span className="welcome-tag">TƯƠNG TÁC TRỰC TIẾP</span></div><div className="section-heading"><div><h2>{view==='saved'?'Mô phỏng của tôi':'Thư viện mô phỏng'}</h2><p>{view==='saved'?'Bài đã lưu trên thiết bị này. Tải HTML để sao lưu.':'Sẵn sàng cho lớp học, không cần kết nối AI.'}</p></div><span className="count">{list.length} mô phỏng</span></div><div className="library-tools"><div className="searchbox"><Search size={18}/><input aria-label="Tìm mô phỏng" placeholder="Tìm mô phỏng, chủ đề…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Xóa tìm kiếm" onClick={()=>setQuery('')}><X size={16}/></button>}</div><Choice label="Lọc môn học" value={filter} onChange={setFilter} items={['Tất cả',...subjects]}/></div><div className="filter-chips">{['Tất cả','Vật lý','Toán học','Hóa học'].map(s=><button key={s} className={filter===s?'selected':''} onClick={()=>setFilter(s)}>{s==='Tất cả'?<BookOpen size={14}/>:s==='Vật lý'?<Atom size={14}/>:s==='Hóa học'?<FlaskConical size={14}/>:<span>ƒ</span>}{s}</button>)}</div>
<div className="lesson-grid">{list.map((l,i)=><article className="lesson-card" key={l.id}><button className={'lesson-preview preview-'+l.kind} aria-label={`Mở ${l.title}`} onClick={()=>setActive(l)}><span className="preview-label">{l.subject}</span><div className="formula-preview">{l.kind==='ohm'?<><span className="formula-big">I <i>=</i> <span className="fraction"><span>U</span><span>R</span></span></span><span className="formula-caption">Điện áp · Điện trở · Dòng điện</span></>:l.kind==='refraction'?<svg viewBox="0 0 300 140"><path d="M0 72H300" stroke="#9fcbdc"/><path d="M150 0V140" stroke="#709aab" strokeDasharray="5 5"/><path d="M66 5L150 72L186 139" stroke="#ffb548" strokeWidth="3" fill="none"/><path d="M150 72L220 5" stroke="#92cbd2" strokeWidth="2" fill="none"/><text x="20" y="56" fill="#c8e7ee" fontSize="12">Không khí</text><text x="20" y="100" fill="#c8e7ee" fontSize="12">Nước</text></svg>:l.kind==='quadratic'?<svg viewBox="0 0 300 140"><path d="M30 112H275M150 5V135" stroke="#a1a1d2"/><path d="M65 5Q150 220 235 5" stroke="#9484f4" strokeWidth="3" fill="none"/><text x="220" y="120" fill="#c5bffa" fontSize="15">y = ax²</text></svg>:<><span className="formula-big">{l.kind==='ph'?'pH':l.kind==='waves'?'∿∿∿':'✦'}</span><span className="formula-caption">{l.kind==='ph'?'Axit — Trung tính — Bazơ':l.kind==='waves'?'Biên độ · Tần số · Bước sóng':'Mô phỏng của bạn'}</span></>}</div><span className="open-preview"><ArrowUpRight size={17}/></span></button><div className="lesson-info"><div className="lesson-meta"><span>{l.grade}</span><span><Monitor size={12}/>Tương tác</span></div><button className="lesson-title" onClick={()=>setActive(l)}>{l.title}</button><p>{l.description}</p><div className="lesson-bottom"><span><Clock size={13}/>{i%2===0?'5–10':'10–15'} phút khám phá</span><button aria-label={view==='saved'?'Xóa bài đã lưu':'Lưu mô phỏng'} onClick={()=>view==='saved'?remove(l.id):save({...l,html:l.html||simulationHTML(l.kind)})}>{view==='saved'?<Trash2 size={17}/>:<FolderHeart size={17}/>}</button></div></div></article>)}</div>{!list.length&&<div className="empty"><Search size={30}/><h3>{view==='saved'?'Chưa có mô phỏng phù hợp':'Chưa tìm thấy chủ đề này'}</h3><p>{view==='saved'?'Lưu mô phỏng yêu thích bằng biểu tượng trái tim.':'Thử từ khóa khác hoặc tạo mô phỏng bằng AI.'}</p><button className="button outline" onClick={()=>{setQuery('');setFilter('Tất cả')}}>Xóa bộ lọc</button></div>}
<div className="teaching-tip"><Lightbulb size={23}/><div><b>Mẹo nhỏ cho một tiết học lớn</b><p>Cho học sinh dự đoán trước khi thay đổi thông số. Quan sát, thảo luận, rồi cùng rút ra quy luật.</p></div></div><div className="bottom-note"><span><ShieldCheck size={15}/> Nội dung AI cần được giáo viên thẩm định</span><span>Học qua trải nghiệm, hiểu bằng khám phá.</span></div></section></div></main>
<Dialog open={settings} onOpenChange={setSettings}><DialogContent className="settings-dialog"><div className="modal-heading"><KeyRound/><div><DialogTitle>Cấu hình AI & API Key</DialogTitle><DialogDescription>Chọn model và thiết lập kết nối AI</DialogDescription></div></div><div className="provider-card"><span className="setup-icon"><Atom/></span><div><b>Google Gemini API</b><p>Kết nối trực tiếp với tài khoản AI của bạn</p></div><Check size={18}/></div><label className="label" htmlFor="api-key">GEMINI API KEY <em>*</em></label><input id="api-key" type="password" autoComplete="off" value={key} onChange={e=>{setKey(e.target.value);setModels([]);setModel('')}} placeholder="Nhập API Key của bạn"/><p className="modal-note">Khóa chỉ giữ trong bộ nhớ phiên, không lưu trên thiết bị hay ghi vào mã nguồn. <a href="https://aistudio.google.com/apikey" target="_blank" rel="noreferrer">Lấy API Key ↗</a></p><button className="button outline" onClick={connect} disabled={checking}>{checking?<LoaderCircle className="spin" size={17}/>:<ShieldCheck size={17}/>}Kiểm tra kết nối & tải model</button><label className="label">MODEL ƯU TIÊN</label>{models.length?<Choice label="Model AI" value={model} onChange={setModel} items={models}/>:<p className="modal-note">Kết nối để hiển thị các model thực sự khả dụng với API Key.</p>}<button className="button primary" disabled={!model} onClick={()=>{setSettings(false);toast.success('Đã áp dụng cấu hình cho phiên này.')}}>Áp dụng cấu hình</button></DialogContent></Dialog>
<Dialog open={help} onOpenChange={setHelp}><DialogContent><DialogTitle>Bắt đầu một bài học tương tác</DialogTitle><DialogDescription>Ba bước để đưa mô phỏng vào lớp học.</DialogDescription><ol className="help-list"><li><b>Chọn một mô phỏng trong thư viện</b><p>Mở bài, điều chỉnh thanh trượt và quan sát kết quả ngay.</p></li><li><b>Tạo theo bài dạy của bạn</b><p>Chọn môn, lớp, nhập chủ đề hoặc tải PDF/ảnh/TXT. Kết nối Gemini trong phần cài đặt để tạo bài mới.</p></li><li><b>Giảng dạy và lưu lại</b><p>Trình chiếu toàn màn hình, lưu trên thiết bị hoặc tải HTML để dùng khi không có internet.</p></li></ol><p className="modal-note">Tệp gửi tới Gemini khi bạn nhấn tạo. Kiểm tra nội dung, công thức và tương tác của bài AI trước khi dùng trong lớp.</p></DialogContent></Dialog>
<Dialog open={!!active} onOpenChange={v=>{if(!v&&!revising.current){setActive(null);setFull(false);setEditing(false);setRevision('')}}}><DialogContent showCloseButton={!revising.current} className={'simulation-dialog '+(full?'presentation':'')}><div className="simulation-top"><div><DialogTitle>{active?.title}</DialogTitle><DialogDescription>{active?.subject} · {active?.grade} {active?.kind==='ai'?'· AI tạo — cần thẩm định':''}</DialogDescription></div><div className="simulation-actions"><button aria-label="Lưu bài" onClick={()=>active&&save({...active,html:active.html||simulationHTML(active.kind)})}><FolderHeart size={19}/></button><button aria-label="Tải HTML dùng ngoại tuyến" onClick={()=>active&&download(active)}><Download size={19}/></button><button aria-label="Chế độ trình chiếu" onClick={()=>setFull(!full)}><Maximize size={19}/></button></div></div>{active&&<iframe title={active.title} sandbox="allow-scripts" referrerPolicy="no-referrer" srcDoc={secureHTML(active.html||simulationHTML(active.kind))}/>}<div className="revision-toolbar"><button className="button outline" disabled={busy} onClick={()=>revise('regenerate')}><RotateCcw size={16}/>Tạo lại</button><button className="button outline" disabled={busy} onClick={()=>setEditing(!editing)} aria-expanded={editing}><PencilLine size={16}/>Chỉnh sửa</button>{revising.current&&<><span role="status"><LoaderCircle size={16} className="spin"/>Đang cập nhật…</span><button className="cancel-revision" onClick={()=>controller.current?.abort()}>Hủy</button></>}</div>{editing&&<div className="revision-editor"><label htmlFor="revision-request">Bạn muốn thêm, bớt hoặc thay đổi điều gì?</label><textarea id="revision-request" value={revision} onChange={e=>setRevision(e.target.value)} aria-describedby="revision-count" aria-invalid={revision.length>TEXT_LIMITS.revision} disabled={busy} rows={2} placeholder="Ví dụ: thêm câu hỏi trắc nghiệm, bỏ phần giải thích dài, đổi màu tia sáng…"/><TextCount field="revision" value={revision} id="revision-count"/><button className="button primary" disabled={busy||!revision.trim()} onClick={()=>revise('edit')}><Sparkles size={16}/>Áp dụng chỉnh sửa</button></div>}<div className="simulation-footer"><Lightbulb size={15}/> Hãy dự đoán → Thay đổi thông số → Quan sát → Giải thích.</div></DialogContent></Dialog></>}
